### ISSUE TITLE
GPU Implementation runs no faster than CPU counterparts

### ISSUE THREAD

**Issue by vwxyzjn** [vwxyzjn/cleanrl#20]
For example, here is the profiling `dqn.py` running 2e4 total timesteps.

GPU:
```
time python dqn.py
real    0m35.960s
user    0m31.977s
sys     0m1.758s
```
![image](https://user-images.githubusercontent.com/5555347/82104842-6dfa8300-96e6-11ea-9481-89cd73d04390.png)

CPU:
```
time python dqn.py --no-cuda
real    0m29.083s
user    5m31.594s
sys     0m9.362s
```
![image](https://user-images.githubusercontent.com/5555347/82104723-017f8400-96e6-11ea-889b-bd04c4219315.png)

**Comment by dosssman** [comment]
On environment that do not require CNN, that is to be expected.

The GPU advantage seems to only kick in when the data / network size crosses a certain threshold,
namely where the overhead of moving the data to the GPU is negligible when compared to the cost of doing the feed forward as well as back propagation operations.

The following Wandb report only investigates the batch size, but the `cuda=True` version seems to become overcome the CPU version around batch size ~7500:
https://app.wandb.ai/dosssman/cleanrl-cpu-gpu-comp/reports/Time-taken-w.r.t.-device--VmlldzoxMzIwNzE

Just to be sure, still need to check without the Wandb logging to make sure it is consistent without the logging overhead.

**Comment by dosssman** [comment]
Well, turns out the Wandb overhead seems to really mess up the results.
When running the experiments with source code on a tmpfs device, the GPU version catches up even faster to the CPU one.

Although incomplete at the time of this writing, the following Wandb Report shows that GPU starts showing faster runtime than CPU from ~512 batch size:
https://app.wandb.ai/dosssman/cleanrl-cpu-gpu-comp-2/reports/Untitled-Report--VmlldzoxMzI0NjU

**Comment by vwxyzjn** [comment]
This has largely been fixed with the latest commits. Closing the issue for now.
