### ISSUE TITLE
Problem with multi-agent atari

### ISSUE THREAD

**Issue by Matkicail** [vwxyzjn/cleanrl#280]
## Problem Description
Trying to run the multi-agent atari games and getting a specific error.
"
AssertionError: `info` dtype is <class 'list'> while supported dtype is `dict`. This may be due to usage of other wrappers in the wrong order.
"

## Checklist
I did not install via poetry since it was giving me this specific error:
File "/usr/lib/python3/dist-packages/poetry/repositories/pypi_repository.py", line 11, in <module>
    from cachecontrol import CacheControl
ModuleNotFoundError: No module named 'cachecontrol'

Followed the outline in this doc for the multi-agent running commands : https://docs.cleanrl.dev/rl-algorithms/ppo/#ppo_pettingzoo_ma_ataripy

## Current Behavior
When trying to run a manually installed version it gives me the above assertion error.
When trying to run the poetry installation it gives me the error in the checklist.

## Expected Behavior
Should be running a multi-agent atari game

## Steps to Reproduce
1. Created conda environment in 3.7.1 Python or 3.9 python and attempt to install using poetry

**Comment by vwxyzjn** [comment]
Thanks for reporting. The error is due to the dependency version (you probably installed gym 0.25.1 but we pinned at 0.23.1). We use poetry to lock versions to specifically avoid this class of issue, and the [CI passes](https://github.com/vwxyzjn/cleanrl/actions/runs/2939411064/jobs/4694517320)

Hmm not sure what happened with poetry installation. Based on a google search [it seems to be related to linux distribution](https://bugs.launchpad.net/ubuntu/+source/poetry/+bug/1958227). You might have to play with it a bit.

Since this is a poetry installation issue I suggest raising a ticket in the poetry repo if you are unable to resolve this issue. I am going to close this issue now.

**Comment by Matkicail** [comment]
Okay thank you for  the assistance.
