### ISSUE TITLE
Is is possible for SAC to support gymnasium too as TD3 and PPO ? 

### ISSUE THREAD

**Issue by qiuruiyu** [vwxyzjn/cleanrl#421]
I'd like to ask for a gymnasium version of SAC in the later updated version of cleanrl. Is it possible ?

**Comment by sdpkjc** [comment]
Hey @qiuruiyu, thanks for your suggestion! You're in luck - @pseudo-rnd-thoughts has been working on a gymnasium version of SAC in #378, and it's nearly ready. There are just a few finishing touches left to do, which I'm planning to wrap up soon. So stay tuned for this update, we think you're going to love it!

**Comment by pseudo-rnd-thoughts** [comment]
Thanks @sdpkjc, I remember running SAC but finding that it was really slow (compared to DDPG or TD3). I believe Costa mentioned that this wasn't an issue but I would confirm if that is still true

**Comment by sdpkjc** [comment]
@pseudo-rnd-thoughts Thank you for your hard work on this! I also had an experience with SAC being considerably slower than DDPG or TD3. I believe it's due to the more complex updating process of the neural networks in SAC, which demands more GPU resources. Indeed, it is slow 😂. Maybe a version with JAX could speed it up.

**Comment by sdpkjc** [comment]
Closed by #378.
